### ISSUE TITLE
supporting activity table for the uuid as a primary key

### ISSUE THREAD

**Issue by siddhant3030** [tfwright/spur#7]
hi.

We are using spur and our activity table needs to have a primary key as a uuid. So we tried few things.

```
defmodule Spur.Activity do
  use Ecto.Schema

  import Ecto.Changeset

  if Application.get_env(:spur, :uuid_primary_key_enabled, false) do
    @primary_key {:id, :binary_id, autogenerate: true}
    @foreign_key_type :binary_id
  end

  schema Application.get_env(:spur, :activities_table_name, "activities") do
    field(:action, :string)
    field(:actor, :string)
    field(:object, :string, default: nil)
    field(:target, :string, default: nil)
    field(:meta, :map, default: %{})

    timestamps(updated_at: false)
  end

  def changeset(%__MODULE__{} = trace, %{} = attrs) do
    trace
    |> cast(attrs, [:action, :actor, :object, :target, :meta])
    |> validate_required([:action, :actor])
  end
end

```

We also changed the table but the problem is when I'm trying to insert any data. I'm getting this error 

(ecto_sql 3.3.4) Ecto.Adapters.Postgres.insert_all(%{cache: #Reference<0.3863175943.1878917121.34711>, opts: [timeout: 15000, pool_size: 10, pool: DBConnection.Ownership], pid: #PID<0.545.0>, repo: WraftDoc.Repo, sql: Ecto.Adapters.Postgres.Connection, telemetry: {Doc.Repo, :debug, [:doc, :repo, :query]}}, %{autogenerate_id: {:id, :id, :binary_id}, context: nil, prefix: nil, schema: Doc.User.Audience, source: "audience"}, [:activity_id, :id, :user_id], [[id: <<244, 234, 198, 131, 31, 236, 78, 69, 143, 179, 141, 46, 181, 141, 44, 104>>, activity_id: <<155, 247, 40, 138, 103, 26, 76, 192, 159, 98, 65, 31, 101, 77, 57, 99>>, user_id: <<241, 145, 112, 154, 33, 177, 66, 160, 165, 124, 63, 44, 114, 225, 180, 160>>]], {:raise, [], []}, [], [], [])

Is there another way to support the uuid ? or any suggestion about this?

**Comment by tfwright** [comment]
Is there any more of your stack trace you can include? And the code that triggers the error?

Obviously this is not something that Spur currently explicitly supports, and it looks like you've changed the source to try and add support? If so, I don't see anything obviously wrong with your implementation.

**Comment by siddhant3030** [comment]
I think I have found the solution. Its actually was something to do with ecto sql version. I changed it to latest one and the issue is gone. Thanks for the input. I can close this issue now.

**Comment by tfwright** [comment]
Glad to hear it. Please feel free to open a PR to add support for this feature so other people can benefit if you can.

**Comment by siddhant3030** [comment]
Sure
